// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';

import '../models/color_info.dart';

List<ColorInfo> colorList = [
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: true,
    isShade300: false,
    isShade200: false,
    isShade100: false,
    name: "red",
    colorCode: Color(0xFFF44336),
    hexCodeColor: "F44336",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: true,
    isShade200: false,
    isShade100: false,
    name: "red-300",
    colorCode: Color(0xFFE57373),
    hexCodeColor: "E57373",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: true,
    isShade100: false,
    name: "red-200",
    colorCode: Color(0xFFEF9A9A),
    hexCodeColor: "EF9A9A",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: false,
    isShade100: true,
    name: "red-100",
    colorCode: Color(0xFFFFCDD2),
    hexCodeColor: "FFCDD2",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: true,
    isShade300: false,
    isShade200: false,
    isShade100: false,
    name: "green",
    colorCode: Color(0xFF4CAF50),
    hexCodeColor: "4CAF50",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: true,
    isShade200: false,
    isShade100: false,
    name: "green-300",
    colorCode: Color(0xFF81C784),
    hexCodeColor: "81C784",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: false,
    isShade200: true,
    isShade100: false,
    name: "green-200",
    colorCode: Color(0xFFA5D6A7),
    hexCodeColor: "A5D6A7",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: false,
    isShade200: false,
    isShade100: true,
    name: "green-100",
    colorCode: Color(0xFFC8E6C9),
    hexCodeColor: "C8E6C9",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: true,
    isShade300: false,
    isShade200: false,
    isShade100: false,
    name: "orange",
    colorCode: Color(0xFFFF9800),
    hexCodeColor: "FF9800",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: true,
    isShade200: false,
    isShade100: false,
    name: "orange-300",
    colorCode: Color(0xFFFFB74D),
    hexCodeColor: "FFB74D",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: true,
    isShade100: false,
    name: "orange-200",
    colorCode: Color(0xFFFFCC80),
    hexCodeColor: "FFCC80",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: false,
    isShade100: true,
    name: "orange-100",
    colorCode: Color(0xFFFFE0B2),
    hexCodeColor: "FFE0B2",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: true,
    isShade300: false,
    isShade200: false,
    isShade100: false,
    name: "yellow",
    colorCode: Color(0xFFFFEB3B),
    hexCodeColor: "FFEB3B",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: true,
    isShade200: false,
    isShade100: false,
    name: "yellow-300",
    colorCode: Color(0xFFFFF176),
    hexCodeColor: "FFF176",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: true,
    isShade100: false,
    name: "yellow-200",
    colorCode: Color(0xFFFFF59D),
    hexCodeColor: "FFF59D",
  ),
  ColorInfo(
    isCoolColor: false,
    isWarmColor: true,
    isMainColor: false,
    isShade300: false,
    isShade200: false,
    isShade100: true,
    name: "yellow-100",
    colorCode: Color(0xFFFFF9C4),
    hexCodeColor: "FFF9C4",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: true,
    isShade300: false,
    isShade200: false,
    isShade100: false,
    name: "blue",
    colorCode: Color(0xFF2196F3),
    hexCodeColor: "2196F3",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: true,
    isShade200: false,
    isShade100: false,
    name: "blue-300",
    colorCode: Color(0xFF64B5F6),
    hexCodeColor: "64B5F6",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: false,
    isShade200: true,
    isShade100: false,
    name: "blue-200",
    colorCode: Color(0xFF90CAF9),
    hexCodeColor: "90CAF9",
  ),
  ColorInfo(
    isCoolColor: true,
    isWarmColor: false,
    isMainColor: false,
    isShade300: false,
    isShade200: false,
    isShade100: true,
    name: "blue-100",
    colorCode: Color(0xFFBBDEFB),
    hexCodeColor: "BBDEFB",
  ),
];
